name: clinica_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.1.1
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  google_sign_in: ^6.1.5
  shared_preferences: ^2.2.2
  pdf: 3.11.3
  printing: ^5.9.0
  path_provider: ^2.0.15
  file_picker: ^5.2.5
  flutter_svg: ^2.0.7

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # ------------------------------
  # Aquí agregamos la sección de assets
  # ------------------------------
  assets:
    - assets/images/logo.png
    - assets/images/           # cualquier otra imagen que agregues en esta carpeta

# Configuración para generar los iconos de la aplicación (launcher icons)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

  # Puedes agregar también fuentes personalizadas si lo deseas
  # fonts:
  #   - family: MiFuente
  #     fonts:
  #       - asset: fonts/MiFuente-Regular.ttf
